/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProtectedRouteImport } from "./routes/_protected";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginIndexRouteImport } from "./routes/login/index";
import { Route as ProtectedTechniciansIndexRouteImport } from "./routes/_protected/technicians/index";
import { Route as ProtectedSettingsIndexRouteImport } from "./routes/_protected/settings/index";
import { Route as ProtectedReviewsIndexRouteImport } from "./routes/_protected/reviews/index";
import { Route as ProtectedReportsIndexRouteImport } from "./routes/_protected/reports/index";
import { Route as ProtectedPayoutsIndexRouteImport } from "./routes/_protected/payouts/index";
import { Route as ProtectedOrdersIndexRouteImport } from "./routes/_protected/orders/index";
import { Route as ProtectedHomeownersIndexRouteImport } from "./routes/_protected/homeowners/index";
import { Route as ProtectedDashboardIndexRouteImport } from "./routes/_protected/dashboard/index";
import { Route as ProtectedCategoriesIndexRouteImport } from "./routes/_protected/categories/index";
import { Route as ProtectedTechniciansTechnicianIdRouteImport } from "./routes/_protected/technicians/$technicianId";
import { Route as ProtectedHomeownersHomeownerIdRouteImport } from "./routes/_protected/homeowners/$homeownerId";

const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedTechniciansIndexRoute =
  ProtectedTechniciansIndexRouteImport.update({
    id: "/technicians/",
    path: "/technicians/",
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedReviewsIndexRoute = ProtectedReviewsIndexRouteImport.update({
  id: "/reviews/",
  path: "/reviews/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedReportsIndexRoute = ProtectedReportsIndexRouteImport.update({
  id: "/reports/",
  path: "/reports/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedPayoutsIndexRoute = ProtectedPayoutsIndexRouteImport.update({
  id: "/payouts/",
  path: "/payouts/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedOrdersIndexRoute = ProtectedOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedHomeownersIndexRoute =
  ProtectedHomeownersIndexRouteImport.update({
    id: "/homeowners/",
    path: "/homeowners/",
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedCategoriesIndexRoute =
  ProtectedCategoriesIndexRouteImport.update({
    id: "/categories/",
    path: "/categories/",
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedTechniciansTechnicianIdRoute =
  ProtectedTechniciansTechnicianIdRouteImport.update({
    id: "/technicians/$technicianId",
    path: "/technicians/$technicianId",
    getParentRoute: () => ProtectedRoute,
  } as any);
const ProtectedHomeownersHomeownerIdRoute =
  ProtectedHomeownersHomeownerIdRouteImport.update({
    id: "/homeowners/$homeownerId",
    path: "/homeowners/$homeownerId",
    getParentRoute: () => ProtectedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login/": typeof LoginIndexRoute;
  "/homeowners/$homeownerId": typeof ProtectedHomeownersHomeownerIdRoute;
  "/technicians/$technicianId": typeof ProtectedTechniciansTechnicianIdRoute;
  "/categories/": typeof ProtectedCategoriesIndexRoute;
  "/dashboard/": typeof ProtectedDashboardIndexRoute;
  "/homeowners/": typeof ProtectedHomeownersIndexRoute;
  "/orders/": typeof ProtectedOrdersIndexRoute;
  "/payouts/": typeof ProtectedPayoutsIndexRoute;
  "/reports/": typeof ProtectedReportsIndexRoute;
  "/reviews/": typeof ProtectedReviewsIndexRoute;
  "/settings/": typeof ProtectedSettingsIndexRoute;
  "/technicians/": typeof ProtectedTechniciansIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginIndexRoute;
  "/homeowners/$homeownerId": typeof ProtectedHomeownersHomeownerIdRoute;
  "/technicians/$technicianId": typeof ProtectedTechniciansTechnicianIdRoute;
  "/categories": typeof ProtectedCategoriesIndexRoute;
  "/dashboard": typeof ProtectedDashboardIndexRoute;
  "/homeowners": typeof ProtectedHomeownersIndexRoute;
  "/orders": typeof ProtectedOrdersIndexRoute;
  "/payouts": typeof ProtectedPayoutsIndexRoute;
  "/reports": typeof ProtectedReportsIndexRoute;
  "/reviews": typeof ProtectedReviewsIndexRoute;
  "/settings": typeof ProtectedSettingsIndexRoute;
  "/technicians": typeof ProtectedTechniciansIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_protected": typeof ProtectedRouteWithChildren;
  "/login/": typeof LoginIndexRoute;
  "/_protected/homeowners/$homeownerId": typeof ProtectedHomeownersHomeownerIdRoute;
  "/_protected/technicians/$technicianId": typeof ProtectedTechniciansTechnicianIdRoute;
  "/_protected/categories/": typeof ProtectedCategoriesIndexRoute;
  "/_protected/dashboard/": typeof ProtectedDashboardIndexRoute;
  "/_protected/homeowners/": typeof ProtectedHomeownersIndexRoute;
  "/_protected/orders/": typeof ProtectedOrdersIndexRoute;
  "/_protected/payouts/": typeof ProtectedPayoutsIndexRoute;
  "/_protected/reports/": typeof ProtectedReportsIndexRoute;
  "/_protected/reviews/": typeof ProtectedReviewsIndexRoute;
  "/_protected/settings/": typeof ProtectedSettingsIndexRoute;
  "/_protected/technicians/": typeof ProtectedTechniciansIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login/"
    | "/homeowners/$homeownerId"
    | "/technicians/$technicianId"
    | "/categories/"
    | "/dashboard/"
    | "/homeowners/"
    | "/orders/"
    | "/payouts/"
    | "/reports/"
    | "/reviews/"
    | "/settings/"
    | "/technicians/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/homeowners/$homeownerId"
    | "/technicians/$technicianId"
    | "/categories"
    | "/dashboard"
    | "/homeowners"
    | "/orders"
    | "/payouts"
    | "/reports"
    | "/reviews"
    | "/settings"
    | "/technicians";
  id:
    | "__root__"
    | "/"
    | "/_protected"
    | "/login/"
    | "/_protected/homeowners/$homeownerId"
    | "/_protected/technicians/$technicianId"
    | "/_protected/categories/"
    | "/_protected/dashboard/"
    | "/_protected/homeowners/"
    | "/_protected/orders/"
    | "/_protected/payouts/"
    | "/_protected/reports/"
    | "/_protected/reviews/"
    | "/_protected/settings/"
    | "/_protected/technicians/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  LoginIndexRoute: typeof LoginIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login/";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/technicians/": {
      id: "/_protected/technicians/";
      path: "/technicians";
      fullPath: "/technicians/";
      preLoaderRoute: typeof ProtectedTechniciansIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/settings/": {
      id: "/_protected/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/reviews/": {
      id: "/_protected/reviews/";
      path: "/reviews";
      fullPath: "/reviews/";
      preLoaderRoute: typeof ProtectedReviewsIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/reports/": {
      id: "/_protected/reports/";
      path: "/reports";
      fullPath: "/reports/";
      preLoaderRoute: typeof ProtectedReportsIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/payouts/": {
      id: "/_protected/payouts/";
      path: "/payouts";
      fullPath: "/payouts/";
      preLoaderRoute: typeof ProtectedPayoutsIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/orders/": {
      id: "/_protected/orders/";
      path: "/orders";
      fullPath: "/orders/";
      preLoaderRoute: typeof ProtectedOrdersIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/homeowners/": {
      id: "/_protected/homeowners/";
      path: "/homeowners";
      fullPath: "/homeowners/";
      preLoaderRoute: typeof ProtectedHomeownersIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/dashboard/": {
      id: "/_protected/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/categories/": {
      id: "/_protected/categories/";
      path: "/categories";
      fullPath: "/categories/";
      preLoaderRoute: typeof ProtectedCategoriesIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/technicians/$technicianId": {
      id: "/_protected/technicians/$technicianId";
      path: "/technicians/$technicianId";
      fullPath: "/technicians/$technicianId";
      preLoaderRoute: typeof ProtectedTechniciansTechnicianIdRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/homeowners/$homeownerId": {
      id: "/_protected/homeowners/$homeownerId";
      path: "/homeowners/$homeownerId";
      fullPath: "/homeowners/$homeownerId";
      preLoaderRoute: typeof ProtectedHomeownersHomeownerIdRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}

interface ProtectedRouteChildren {
  ProtectedHomeownersHomeownerIdRoute: typeof ProtectedHomeownersHomeownerIdRoute;
  ProtectedTechniciansTechnicianIdRoute: typeof ProtectedTechniciansTechnicianIdRoute;
  ProtectedCategoriesIndexRoute: typeof ProtectedCategoriesIndexRoute;
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute;
  ProtectedHomeownersIndexRoute: typeof ProtectedHomeownersIndexRoute;
  ProtectedOrdersIndexRoute: typeof ProtectedOrdersIndexRoute;
  ProtectedPayoutsIndexRoute: typeof ProtectedPayoutsIndexRoute;
  ProtectedReportsIndexRoute: typeof ProtectedReportsIndexRoute;
  ProtectedReviewsIndexRoute: typeof ProtectedReviewsIndexRoute;
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute;
  ProtectedTechniciansIndexRoute: typeof ProtectedTechniciansIndexRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeownersHomeownerIdRoute: ProtectedHomeownersHomeownerIdRoute,
  ProtectedTechniciansTechnicianIdRoute: ProtectedTechniciansTechnicianIdRoute,
  ProtectedCategoriesIndexRoute: ProtectedCategoriesIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedHomeownersIndexRoute: ProtectedHomeownersIndexRoute,
  ProtectedOrdersIndexRoute: ProtectedOrdersIndexRoute,
  ProtectedPayoutsIndexRoute: ProtectedPayoutsIndexRoute,
  ProtectedReportsIndexRoute: ProtectedReportsIndexRoute,
  ProtectedReviewsIndexRoute: ProtectedReviewsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedTechniciansIndexRoute: ProtectedTechniciansIndexRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
