sonar.projectKey=FixIt
sonar.projectName=FixIt
sonar.sourceEncoding=UTF-8

sonar.sources=apps/native/src,apps/server/src,packages/db/src,packages/env/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/.expo/**,apps/native/android/**,apps/native/ios/**,apps/server/serverless-deploy/**,**/*.d.ts

sonar.typescript.tsconfigPaths=apps/native/tsconfig.json,apps/server/tsconfig.json,packages/db/tsconfig.json,packages/env/tsconfig.json
sonar.typescript.lcov.reportPaths=apps/server/coverage/lcov.info
