# "service" is the name of this project. This will also be added to your AWS resource names.
service: FixIt

build:
  esbuild:
    banner:
      js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);"
    bundle: true
    format: esm
    platform: node
    target: node20
    external:
      - "@supabase/supabase-js"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
    SUPABASE_CONNECTION_STRING: ${env:SUPABASE_CONNECTION_STRING}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
    STORAGE_BUCKET: ${env:STORAGE_BUCKET}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  auth:
    handler: serverless-deploy/auth-lambda.handler
    events:
      - httpApi:
          path: /api/auth/{proxy+}
          method: ANY

  technicianAuth:
    handler: serverless-deploy/technician-auth-lambda.handler
    events:
      - httpApi:
          path: /api/technician-auth/{proxy+}
          method: ANY
  users:
    handler: serverless-deploy/users-lambda.handler
    events:
      - httpApi:
          path: /api/users/{proxy+}
          method: ANY

  technicians:
    handler: serverless-deploy/technicians-lambda.handler
    events:
      - httpApi:
          path: /api/categories/:categoryId/technicians/{proxy+}
          method: ANY

  addresses:
    handler: serverless-deploy/addresses-lambda.handler
    events:
      - httpApi:
          path: /api/addresses/{proxy+}
          method: ANY
  categories:
    handler: serverless-deploy/categories-lambda.handler
    events:
      - httpApi:
          path: /api/categories/{proxy+}
          method: ANY

  technicianCalendar:
    handler: serverless-deploy/technician-calendar-lambda.handler
    events:
      - httpApi:
          path: /api/technician-calendar/{proxy+}
          method: ANY

  services:
    handler: serverless-deploy/services-lambda.handler
    events:
      - httpApi:
          path: /api/categories/:categoryId/services/{proxy+}
          method: ANY
