import { hairlineWidth } from "nativewind/theme";
import type { Config } from "tailwindcss";

const config: Config = {
	content: [
		"./src/**/*.{js,jsx,ts,tsx}",
		"./src/app/**/*.{js,jsx,ts,tsx}",
		"./src/components/**/*.{js,jsx,ts,tsx}",
		"./src/features/**/*.{js,jsx,ts,tsx}",
	],
	presets: [require("nativewind/preset")],
	theme: {
		extend: {
			colors: {
				// ─── shadcn / rn-primitives semantic tokens (HSL CSS vars) ──
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},

				// ─── App colors (all from runtime theme variables) ──
				"app-primary": {
					DEFAULT: "var(--app-primary)",
					light: "var(--app-primary-light)",
					dark: "var(--app-primary-dark)",
				},
				content: {
					DEFAULT: "var(--text-primary)",
					secondary: "var(--text-secondary)",
					muted: "var(--text-muted)",
				},
				edge: { DEFAULT: "var(--border-default)", chip: "var(--border-chip)" },
				success: { DEFAULT: "var(--success)", alt: "var(--success-alt)" },
				danger: {
					DEFAULT: "var(--danger)",
					light: "var(--danger-light)",
					soft: "var(--danger-soft)",
				},
				warning: { DEFAULT: "var(--warning)", light: "var(--warning-light)" },
				surface: {
					DEFAULT: "var(--surface-base)",
					elevated: "var(--surface-elevated)",
					muted: "var(--surface-muted)",
				},
				star: {
					DEFAULT: "var(--rating-default)",
					light: "var(--rating-light)",
				},
				status: {
					available: "var(--status-available)",
					online: "var(--status-online)",
					unavailable: "var(--status-unavailable)",
					"unavailable-bg": "var(--status-unavailable-bg)",
				},
				order: { bg: "var(--order-bg)", text: "var(--order-text)" },
				"accent-cyan": "var(--accent-cyan)",
				"accent-purple": "var(--accent-purple)",
				"accent-sky": "var(--accent-sky)",
				role: {
					user: "var(--role-user)",
					tech: "var(--role-tech)",
					accent: "var(--role-accent)",
					label: "var(--role-label)",
				},
				overlay: {
					white: "var(--overlay-white)",
					md: "var(--overlay-md)",
					sm: "var(--overlay-sm)",
					sub: "var(--overlay-sub)",
					dim: "var(--overlay-dim)",
					bright: "var(--overlay-bright)",
				},
				gradient: {
					start: "var(--gradient-start)",
					mid: "var(--gradient-mid)",
					end: "var(--gradient-end)",
					"role-start": "var(--gradient-role-start)",
					"role-mid": "var(--gradient-role-mid)",
					"role-end": "var(--gradient-role-end)",
				},
				shadow: "var(--shadow)",
				social: "var(--social-icon)",
				disabled: "var(--disabled-text)",
				calendar: "var(--text-calendar)",
				contrast: "var(--text-contrast)",
				category: {
					cyan: "var(--category-cyan)",
					indigo: "var(--category-indigo)",
					red: "var(--category-red)",
					green: "var(--category-green)",
					rose: "var(--category-rose)",
					purple: "var(--category-purple)",
					blue: "var(--category-blue)",
					brown: "var(--category-brown)",
					orange: "var(--category-orange)",
				},
			},
			borderRadius: {
				// var-backed shadcn radii (preserve — do not rename)
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
				// fixed-pixel semantic radii (new — mirrors design-tokens/radius.ts)
				card: "16px",
				input: "12px",
				button: "12px",
				sheet: "20px",
				chip: "9999px",
				pill: "9999px",
				"control-segmented": "12px",
				"control-segmented-item": "8px",
			},
			height: {
				"btn-sm": "36px",
				"btn-md": "48px",
				"btn-lg": "56px",
				"btn-xl": "64px",
				"control-back-sm": "36px",
				"control-back-md": "40px",
				"control-chip": "32px",
				"control-search": "44px",
				"control-segmented-item": "40px",
				input: "56px",
				header: "64px",
				"tab-bar": "72px",
				"avatar-sm": "40px",
				"avatar-md": "48px",
				"avatar-lg": "56px",
				"avatar-xl": "64px",
				"avatar-2xl": "96px",
				"control-icon-box-sm": "32px",
				"control-icon-box-md": "40px",
				"control-icon-box-touch": "44px",
				"control-icon-box-lg": "48px",
			},
			width: {
				"control-back-sm": "36px",
				"control-back-md": "40px",
				"avatar-sm": "40px",
				"avatar-md": "48px",
				"avatar-lg": "56px",
				"avatar-xl": "64px",
				"avatar-2xl": "96px",
				"icon-xs": "16px",
				"icon-sm": "20px",
				"icon-md": "24px",
				"icon-lg": "32px",
				"icon-xl": "40px",
				"control-icon-box-sm": "32px",
				"control-icon-box-md": "40px",
				"control-icon-box-touch": "44px",
				"control-icon-box-lg": "48px",
			},
			minHeight: {
				header: "64px",
			},
			padding: {
				"screen-x": "20px",
				"screen-y": "16px",
				card: "16px",
				"card-compact": "12px",
				"card-roomy": "20px",
				sheet: "20px",
				"control-search": "14px",
				"control-btn-compact": "12px",
				"control-chip": "16px",
				"control-action-y": "16px",
				"control-cta-y": "14px",
				"control-compact-cta-x": "20px",
				"control-compact-cta-y": "10px",
				"control-segmented-shell": "4px",
				"control-segmented-x": "12px",
				"control-pill-x": "16px",
				"control-pill-y": "6px",
				"control-trigger-x": "12px",
				"control-trigger-y": "8px",
				"control-badge-x": "8px",
				"control-badge-y": "2px",
				"list-row-y": "14px",
				"list-row-comfortable-y": "16px",
			},
			gap: {
				"stack-xs": "4px",
				"stack-sm": "8px",
				"stack-md": "12px",
				"stack-lg": "16px",
				"stack-xl": "24px",
				"control-search": "10px",
				"control-btn-compact": "6px",
				"control-action": "8px",
				"control-cta": "8px",
				"control-trigger": "6px",
				"control-chip": "8px",
				"control-badge": "4px",
				"control-segmented": "6px",
				"list-row": "12px",
				"card-compact": "8px",
				"card-roomy": "16px",
			},
			borderWidth: {
				hairline: hairlineWidth(),
			},
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
		},
	},
	future: {
		hoverOnlyWhenSupported: true,
	},
	plugins: [require("tailwindcss-animate")],
};

export default config;
